### ISSUE TITLE
Main menu implementation assets in unity

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#118]
use design by @Nabalrog

**Comment by irtazakhan** [comment]
Visual Implementation of Menu -  #134

**Comment by irtazakhan** [comment]
Volume Setting linked to Code - #136

**Comment by irtazakhan** [comment]
Restructure Main Menu v3 Canvases - #138

**Comment by fominykh** [comment]
Let's keep this issue in Milestone 11. It looks like it is done or almost done.

**Comment by alxyzz** [comment]
Control scheme setting mechanic still waiting on @eleonoranava to hash out some things.

**Comment by Nabalrog** [comment]
Closed, remaining changes on issue #194
