### ISSUE TITLE
Redesign of the Tablet UI

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#131]
Continue working on the Table UI design.
Milestone-09 -> Milestone-10 -> Milestone-11 -> Milestone-12

**Comment by eleonoranava** [comment]
Figma file: https://www.figma.com/file/Uc60rLk4P67ikJ2xF2FHfs/Tabletdesignv2single2?type=design&node-id=0%3A1&mode=design&t=yXeiBGqfLfM4h62J-1
Previous design Figma file: https://www.figma.com/file/weqXJwW0RBJ3ycZfAsJCsT/Ui-Ux-Design-VR4VET?type=design&node-id=0%3A1&mode=design&t=nXF9vYgxDeNcDN3s-1

**Comment by fominykh** [comment]
Design feedback: 
Task list : 
* too much empty space
* the arrows are too small - hard to click in VR
* active support buttons are too small.
The Task screen:
* The back button is too small, while the name of the task is not clickable. The name should be part of the button.
* The Home button is a good - no space around.
