### ISSUE TITLE
UX for the selection of single- vs multi-user mode

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#133]
possibly to integrate this into the onboarding scene?
in the reception area, we can have a screen with list of active rooms

**Comment by ottedam** [comment]
Currently present in supervisor branch:
Players are only connected to the server when clicking the connect button
Players can click on a room and will be loaded into the scene that is specified for that particular room

**Comment by alxyzz** [comment]
Duplicate, separated in #154 and #155 but has relevant info.
