### ISSUE TITLE
Test tablet tracking and falling objects

### ISSUE THREAD

**Issue by ottedam** [vr4vet/vr4vet#145]
Fixes were made for tablet tracking and hand held objects falling to the ground. These need to be tested

**Comment by fominykh** [comment]
Do we even need to synchronize the table(s) between multiple users, @ottedam ? What was the argumentation here?

**Comment by ottedam** [comment]
@fominykh When players look at their tablet it seems weird for other users in the environment. Not a hard requirement. Andreas told me that it was discussed in the meeting that it is better to focus on other tasks first.

**Comment by ottedam** [comment]
Falling objects has been fixed. Tablet tracking will be postponed until later
