### ISSUE TITLE
Onboarding Multi-User - Room Selector Implementation

### ISSUE THREAD

**Issue by alxyzz** [vr4vet/vr4vet#154]
depends on #153

needs a meeting (~9th August?)

**Comment by ottedam** [comment]
The selection should be done on a computer screen. Users should be able to create a room or join a room. Joining a room could be done with a code. For instance tell your friend to join with the code '1234'.

**Comment by ottedam** [comment]
First implementation is done. Needs to get an update when new changes come to the UI
