### ISSUE TITLE
Increase carrying capacity of the VR player

### ISSUE THREAD

**Issue by ottedam** [vr4vet/vr4vet#166]
Right now the user can carry 2 items in the holster, of which one is the tablet already. This can create issues when multiple grabbable objects have to be moved from one place to the other. Ideas to fix it is to allow multiple items in one circle of the holder or increase the number of circles an item can be placed in. Ideally there would be 6 items including the tablet.

**Comment by AndreasAch** [comment]
Played around a bit with a first mockup for an inventory system that uses sockets. Right now the popup menu is linked to the 'X' button on the left controller

![InventoryMock](https://github.com/vr4vet/vr4vet/assets/56634061/5e999386-a29b-487d-a482-91dcb9c6446e)

**Comment by AndreasAch** [comment]
Small demo of the current inventory functionality

https://github.com/vr4vet/vr4vet/assets/56634061/9b5b6906-6fce-4c90-b13c-cc1917ada302

**Comment by AndreasAch** [comment]
Package v1.0 for the inventory just released.
