### ISSUE TITLE
Onboarding scene

### ISSUE THREAD

**Issue by fominykh** [vr4vet/vr4vet#19]
This task is to implement the "Onboarding scene" in the "Template".
An onboarding scene is a scene that first loads when a workspace app is started.
An onboarding scene should (these will be separate issues):
1. introduce the experience for the user (starts automatically on first launch, can be skipped, can be switched off in the menu) https://github.com/vr4vet/vr4vet/issues/151
2. introduce the controls and teleportation, teaching the user who is new to VR (starts automatically on first launch, can be skipped, can be switched off in the menu - this is device dependent) - has own issues here: #38 #37 
3. Wizard through the settings, allowing to set language, audio settings, etc. https://github.com/vr4vet/vr4vet/issues/37

**Comment by ingolvjr** [comment]
The tutorial is pretty much complete now, the "Open menu" part of the tutorial is currently impossible to complete and the custom font for the tooltipsare also missing, but will probably work just fine once merged with a branch that has it.

**Comment by ingolvjr** [comment]
Latsest relevant commit: d5bc9b4
