### ISSUE TITLE
Tablet pagination breaks when completing task

### ISSUE THREAD

**Issue by trthingnes** [vr4vet/vr4vet#255]
Related to #239.

When a subtask is completed using `Subtask::Compleate(true)` the pagination on the tablet task list breaks.
This means that all the subtasks are listed and exit the tablet.

When the user goes back and presses the task again the problem resolves itself.

**Comment by ingolvjr** [comment]
The problem is the UpdateCheckmark() method in tasklistholder1 reloading all the subtasks and doesn't limit the amount of displayed entries.
