### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/vr4vet#258]
Unable to build in VR4VET repo due to PrefabUtility in TooltipManager.cs that uses UnityEditor.

**Comment by qlpham231** [comment]
@SnorreForbregd, something you could maybe look at?

**Comment by SnorreForbregd** [comment]
Thought I had fixed this earlier, but I probably just fixed it locally. Know the solution, should only take 10 minutes or so

**Comment by SnorreForbregd** [comment]
Issue was a different one than I expected, but the required solution was similar.
