### ISSUE TITLE
Connect AI solution to project

### ISSUE THREAD

**Issue by FridaLar** [vr4vet/vr4vet#279]
This issue is about successfully connecting the chosen AI API with the relevant NPC code.

**Comment by nicoljn19** [comment]
- [x] The solution to the issue has been reviewed by the relevant project manager and at least one other development team member who did not work on the issue.
- [x] If relevant, at least one unit test has been implemented and runs successfully in the code file. 
- [x] If relevant, at least one usability test has been performed successfully without finding any unforeseen issues.
- [x] If relevant, documentation has been updated appropriately.
- [x] The amount of time spent on the issue during “In Progress” is noted in the backlog.
- [x] The amount of time spent on testing the issue during “In Review” is noted in the backlog. 
- [x] The issue has been moved from “In progress” to “Done” in the backlog.
