### ISSUE TITLE
Improve audio file saving

### ISSUE THREAD

**Issue by nicoljn19** [vr4vet/vr4vet#290]
This issue is about improving the solution for audio files. Right now, we have copied code which could be rewritten or replaced with an appropriate package. Additionally, all recorded audio files should be deleted after transcription. Right now they remain. It may also be worth exploring and testing how saving audio files works on different devices with a VR headset.

https://discussions.unity.com/t/delete-sound-assets-during-gameplay/146394

- [x] The solution to the issue has been reviewed by the relevant project manager and at least one other development team member who did not work on the issue.
- [x] If relevant, at least one unit test has been implemented and runs successfully in the code file. 
- [x] If relevant, at least one usability test has been performed successfully without finding any unforeseen issues.
- [x] If relevant, documentation has been updated appropriately.
- [x] The amount of time spent on the issue during “In Progress” is noted in the backlog.
- [x] The amount of time spent on testing the issue during “In Review” is noted in the backlog. 
- [x] The issue has been moved from “In progress” to “Done” in the backlog.

**Comment by iverri** [comment]
Very good! Works as intended!
