### ISSUE TITLE
Adapt AI answers' context and length

### ISSUE THREAD

**Issue by runesee** [vr4vet/vr4vet#304]
This issue is about playing around with context prompts for the AI queries. For example, in the fish feeding scene, we can have something like, "You are a friendly supervisor in a fish feeding factory." As a result, the answers to queries may be better.
- [x] The solution to the issue has been reviewed by the relevant project manager and at least one other development team member who did not work on the issue.
- [x] If relevant, at least one unit test has been implemented and runs successfully in the code file. 
- [x] If relevant, at least one usability test has been performed successfully without finding any unforeseen issues.
- [x] If relevant, documentation has been updated appropriately.
- [x] The amount of time spent on the issue during “In Progress” is noted in the backlog.
- [x] The amount of time spent on testing the issue during “In Review” is noted in the backlog. 
- [x] The issue has been moved from “In progress” to “Done” in the backlog.

**Comment by JohsGronstad** [comment]
Added support for developers to define their own context prompt and max tokens when creating NPCs.
