### ISSUE TITLE
Create our own template scene and NPC prefab

### ISSUE THREAD

**Issue by runesee** [vr4vet/vr4vet#305]
This issue is about creating our own template scene and NPC prefab in Unity. So far, we have been editing an already existing prefab which is not ideal if the project is gonna be merged into main in the future. We can simply duplicate the already existing ones and remove what we do not need. For the original template scene, we should revert all changes.
- [x] The solution to the issue has been reviewed by the relevant project manager and at least one other development team member who did not work on the issue.
- [x] If relevant, at least one unit test has been implemented and runs successfully in the code file. 
- [x] If relevant, at least one usability test has been performed successfully without finding any unforeseen issues.
- [x] If relevant, documentation has been updated appropriately.
- [x] The amount of time spent on the issue during “In Progress” is noted in the backlog.
- [x] The amount of time spent on testing the issue during “In Review” is noted in the backlog. 
- [x] The issue has been moved from “In progress” to “Done” in the backlog.

**Comment by nicoljn19** [comment]
The old template scene does show some errors since we had to edit the original code slightly, but this does not affect the functionality of the scene. These can be ignored and commented out later.
