### ISSUE TITLE
Add AI text box when dialogue ends

### ISSUE THREAD

**Issue by nicoljn19** [vr4vet/vr4vet#309]
This issue is about adding a new text box after predetermined dialogue is done, where AI answers can be inserted.
- [x] The solution to the issue has been reviewed by the relevant project manager and at least one other development team member who did not work on the issue.
- [x] If relevant, at least one unit test has been implemented and runs successfully in the code file. 
- [x] If relevant, at least one usability test has been performed successfully without finding any unforeseen issues.
- [x] If relevant, documentation has been updated appropriately.
- [x] The amount of time spent on the issue during “In Progress” is noted in the backlog.
- [x] The amount of time spent on testing the issue during “In Review” is noted in the backlog. 
- [x] The issue has been moved from “In progress” to “Done” in the backlog.

**Comment by iverri** [comment]
Issue for further development:
User is able to input a new question before the other has been dictated. This will override the previous dictation but not the textbox. Maybe implement a limitation such that the user cannot send a new question before the last one has started dictation.

**Comment by iverri** [comment]
To test the functionality:
1. Go through Bob the Builders dialogue tree with the skip button
2. When you have come all the way through the skip button will disappear and the NPC will say "That's all I have to say. Do you have any questions? Hold B to speak to me."
3. Try asking a question
4. The dialogue box will display "I'm thinking" while the program is waiting for a response from the API
5. When the response has arrived it should display in the dialogue box and be spoken by the NPC at the same time
