### ISSUE TITLE
Create Tooltip Design

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/vr4vet#74]
Sub-issue from #73

(i) Tooltip [X]
___________________
text of the tooltip
___________________

Should use VR4VET brand colors
Animations: On appearance, Idle, On closing
Sound effects: Intent is to notify the user that there is a tooltip in that location

**Comment by olivierdikken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[tooltip] Create a way to annotate and display/playback contextual (3d objects) messages in the form of texts or audio clips.](https://trello.com/c/uZptqxCg/90-tooltip-create-a-way-to-annotate-and-display-playback-contextual-3d-objects-messages-in-the-form-of-texts-or-audio-clips)
