### ISSUE TITLE
Tooltip Activation

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/vr4vet#76]
Sub-issue from #73 

Figure out developer-friendly ways to activate and deactivate tooltips.

activation/deactivation conditions: triggered by events
-- (a) automatic (e.g., in the first time use of the app)
-- (b) manual (by pointing at an object with the laser pointer with a 0,5 seconds delay, needs to be tested if this works)
displaying conditions (distance, view angle, ...)
interaction (hide it by another laser click)
rotate 2d tooltip UI to face HMD

**Comment by olivierdikken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[tooltip] Create a way to annotate and display/playback contextual (3d objects) messages in the form of texts or audio clips.](https://trello.com/c/uZptqxCg/90-tooltip-create-a-way-to-annotate-and-display-playback-contextual-3d-objects-messages-in-the-form-of-texts-or-audio-clips)

**Comment by olivierdikken** [comment]
![image](https://user-images.githubusercontent.com/112614548/219336543-44c201e9-69ef-4821-8b94-b9a9cdf660b2.png)
