### ISSUE TITLE
Tooltip manager with option to close all other tooltips when a new one is opened

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/vr4vet#91]
Have a tooltip manager that automatically closes all other tooltips when a new tooltip is opened.

**Comment by fominykh** [comment]
Does it mean that we give up on the idea of having multipole tooltips open at the same time? Or we give it up just for now?

**Comment by SnorreForbregd** [comment]
Only for now, to have a better product while working on having multiple tooltips.

Closed with commit [cba8cba](https://github.com/vr4vet/vr4vet/commit/cba8cbaf308a0252910b62e8c6294e8aec0d26d5) in [features/add-customizable-tooltips](https://github.com/vr4vet/vr4vet/tree/features/add-customizable-tooltips)
